" Windows-specific fixes for annoying behaviors
if has('win32') || has('win64')
  set runtimepath=$HOME/_vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$HOME/_vim/after
endif 
" Save all backups here, rather than spreading around the file system.
" %TEMP% is Windows-specific
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp,%TEMP%
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp,%TEMP%

set noswapfile
set nobackup

set ignorecase
set splitbelow
set splitright
set ruler  " Ruler on
set number
set nowrap  " Line wrapping off
set timeoutlen=300  " Time to wait after ESC (default causes an annoying delay)

set tabstop=2  " Tabs are 2 spaces
set backspace=2  " Backspace over everything in insert mode
set shiftwidth=2  " Tabs under smart indent

set cindent
set autoindent
set smarttab
set expandtab

set showmatch  " Show matching brackets.
set mat=5  " Bracket blinking.

set mouse=a " enable mouse clicks on folders/files in nerdtree

set wildmenu " make tab completion more like bash
set wildignore=*.swp
set wildmode=list:longest

"Auto size the active window to take up 70% of screen
" let &winheight = &lines * 7/10
" let &winwidth = &columns * 7/10

" Disable beeping and blinking on error
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

set guitablabel=%N/\ %t\ %M " show tab number in tabline

set hlsearch      " highlight all occurrences of search term
:highlight clear Search
:highlight Search term=reverse ctermfg=0 ctermbg=3 guibg=Yellow
set ignorecase    " ignore case when searching

filetype plugin on
filetype indent on
syntax on

if has("autocmd")
  autocmd FileType html,css setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
  autocmd FileType ruby,cucumber,haml setlocal expandtab shiftwidth=2 softtabstop=2
  autocmd FileType javascript setlocal expandtab shiftwidth=2 softtabstop=2
  autocmd FileType php setlocal shiftwidth=2 tabstop=2
  autocmd FileType markdown setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2 wrap nolist
  autocmd BufRead,BufNewFile *.jsx.erb set filetype=eruby.javascript

  " lets view some images in iterm!
  autocmd BufEnter *.png,*.jpg,*gif exec "! open ".expand("%") | :bw
endif

so ~/.vim/plugins.vim
so ~/.vim/plugin-config.vim
so ~/.vim/stitchfix.vim
so ~/.vim/cheat.vim
so ~/.vim/keys-commands.vim
